CREATE DATABASE idx;
USE idx;
CREATE TABLE n (id INT, v INT, s VARCHAR(20));
INSERT INTO n (id, v, s) VALUES (1, 10, 'aa');
INSERT INTO n (id, v, s) VALUES (2, 20, 'bb');
INSERT INTO n (id, v, s) VALUES (3, 30, 'cc');
INSERT INTO n (id, v, s) VALUES (4, 40, 'dd');
INSERT INTO n (id, v, s) VALUES (5, 50, 'ee');
CREATE INDEX i_v ON n (v);
CREATE INDEX i_s ON n (s);
SELECT id FROM n WHERE v >= 20;
SELECT id FROM n WHERE v <= 40;
SELECT id FROM n WHERE v >= 20 AND v <= 40;
SELECT id FROM n WHERE v > 20 AND v < 50;
SELECT id FROM n WHERE v BETWEEN 20 AND 40;
SELECT id FROM n WHERE v = 30;
SELECT id FROM n WHERE s = 'cc';
SELECT id, s FROM n WHERE s = 'cc' AND v = 30;
SELECT id FROM n WHERE s = 'dd' OR v = 10;
SELECT id FROM n WHERE v > 45;
SELECT id FROM n WHERE v < 15;
UPDATE n SET v = 35 WHERE id = 2;
SELECT id, v FROM n WHERE v >= 20 AND v <= 40;
SELECT id, v FROM n WHERE v = 35;
INSERT INTO n (id, v, s) VALUES (6, 5, 'ff');
SELECT id FROM n WHERE v < 20;
DELETE FROM n WHERE id = 1;
SELECT id FROM n WHERE v = 10;
SELECT id FROM n WHERE s = 'aa';
