CREATE DATABASE edge;
USE edge;
CREATE TABLE t (id INT, txt VARCHAR(20), num DOUBLE, flag BOOLEAN, d DATETIME);
INSERT INTO t (id, txt, num, flag, d) VALUES (1, 'alpha', 1.5, TRUE, '2025-01-01 10:00:00');
INSERT INTO t (id, txt, num, flag, d) VALUES (2, NULL, -3.25, FALSE, '2025-02-01 11:30:00');
INSERT INTO t (id, txt, num, flag, d) VALUES (3, 'gamma', 0, NULL, NULL);
INSERT INTO t (id, txt, num, flag, d) VALUES (4, 'Alpha', 7, TRUE, '2025-03-01 09:00:00');
SELECT * FROM t;
SELECT id FROM t WHERE txt IS NULL;
SELECT id FROM t WHERE txt IS NOT NULL;
SELECT id, txt FROM t WHERE txt LIKE '%lph%';
SELECT id FROM t WHERE num < 0;
SELECT id, num FROM t WHERE num BETWEEN -5 AND 2;
SELECT id FROM t WHERE flag = TRUE;
SELECT id, txt FROM t WHERE txt NOT LIKE 'a%';
SELECT COUNT(*) AS all_rows, COUNT(txt) AS txt_rows FROM t;
SELECT id FROM t ORDER BY num DESC, id ASC;
SELECT DISTINCT flag FROM t;
SELECT id FROM t LIMIT 2 OFFSET 1;
SELECT id, (num + 1) * 2 AS calc FROM t WHERE id < 3;
SELECT id FROM t WHERE id = 1 OR id = 3;
SELECT id FROM t WHERE NOT (id = 1);
SELECT id FROM t WHERE d > '2025-01-15';
CREATE INDEX idx_id ON t (id);
SELECT id, txt FROM t WHERE id = 3;
SELECT id, txt FROM t WHERE id >= 2 AND id <= 4;
UPDATE t SET txt = 'ALPHA' WHERE id = 1;
SELECT id, txt FROM t WHERE id = 1;
DELETE FROM t WHERE id = 3;
SELECT COUNT(*) AS n FROM t;
