Imports System.Collections.Generic
Imports System.IO

Namespace Storage

    ''' <summary>
    ''' file naming rules of the table storage layout:
    '''
    '''   &lt;table&gt;.schema.json   the table schema (columns, comment, keys)
    '''   &lt;table&gt;.jsonl         the row data, one json object per line, managed by JsonlStore
    '''   &lt;table&gt;.jsonl.wal     the write ahead log of the jsonl store
    '''   &lt;table&gt;.jsonl.idx     the sparse line index of the jsonl store
    '''   &lt;table&gt;.jsonl.lock    the exclusive open lock of the jsonl store
    '''   &lt;table&gt;.json          the legacy single file table (read only, migrated on write)
    ''' </summary>
    Public Class StorageLayout

        Public Const DataExtension As String = ".jsonl"
        Public Const SchemaExtension As String = ".schema.json"
        Public Const LegacyExtension As String = ".json"
        Public Const LegacyBackupExtension As String = ".json.bak"

        ''' <summary>the suffixes generated by the jsonl store engine itself</summary>
        Public Shared ReadOnly CompanionSuffixes As String() = {
            ".wal", ".idx", ".idx.tmp", ".lock", ".bak", ".merge.tmp", ".oldbak"
        }

        Public Shared Function DataPath(dbDir As String, table As String) As String
            Return Path.Combine(dbDir, table & DataExtension)
        End Function

        Public Shared Function SchemaPath(dbDir As String, table As String) As String
            Return Path.Combine(dbDir, table & SchemaExtension)
        End Function

        Public Shared Function LegacyPath(dbDir As String, table As String) As String
            Return Path.Combine(dbDir, table & LegacyExtension)
        End Function

        Public Shared Function LegacyBackupPath(dbDir As String, table As String) As String
            Return Path.Combine(dbDir, table & LegacyBackupExtension)
        End Function

        ''' <summary>all index files and the lock file of one table</summary>
        Public Shared Function CompanionFiles(dbDir As String, table As String) As List(Of String)
            Dim files As New List(Of String)
            Dim data As String = DataPath(dbDir, table)

            For Each suffix As String In CompanionSuffixes
                files.Add(data & suffix)
            Next

            Return files
        End Function

        Public Shared Function IsSchemaFile(fileName As String) As Boolean
            Return fileName.EndsWith(SchemaExtension, StringComparison.OrdinalIgnoreCase)
        End Function

        Public Shared Function IsDataFile(fileName As String) As Boolean
            Return fileName.EndsWith(DataExtension, StringComparison.OrdinalIgnoreCase)
        End Function

        ''' <summary>true for the auxiliary files created by the jsonl store engine</summary>
        Public Shared Function IsCompanionFile(fileName As String) As Boolean
            For Each suffix As String In CompanionSuffixes
                If fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase) Then
                    Return True
                End If
            Next

            Return False
        End Function

        ''' <summary>
        ''' resolve the table name of one file, nothing when the file does not belong
        ''' to a table (index files, wal, lock, backup files ...).
        ''' </summary>
        Public Shared Function TableNameOf(fileName As String) As String
            If IsCompanionFile(fileName) OrElse
               fileName.EndsWith(LegacyBackupExtension, StringComparison.OrdinalIgnoreCase) Then
                Return Nothing
            End If

            If IsSchemaFile(fileName) Then
                Return fileName.Substring(0, fileName.Length - SchemaExtension.Length)
            End If

            If IsDataFile(fileName) Then
                Return fileName.Substring(0, fileName.Length - DataExtension.Length)
            End If

            If fileName.EndsWith(LegacyExtension, StringComparison.OrdinalIgnoreCase) Then
                Return fileName.Substring(0, fileName.Length - LegacyExtension.Length)
            End If

            Return Nothing
        End Function

        ''' <summary>
        ''' discover the table names inside a database folder. auxiliary files and
        ''' backup files are filtered out, the result is de-duplicated and sorted.
        ''' </summary>
        Public Shared Function ListTables(dbDir As String) As List(Of String)
            Dim names As New List(Of String)

            If Not Directory.Exists(dbDir) Then
                Return names
            End If

            Dim seen As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase)

            For Each file As String In Directory.GetFiles(dbDir)
                Dim table As String = TableNameOf(Path.GetFileName(file))

                If table IsNot Nothing AndAlso table.Length > 0 AndAlso seen.Add(table) Then
                    names.Add(table)
                End If
            Next

            names.Sort(StringComparer.OrdinalIgnoreCase)
            Return names
        End Function
    End Class
End Namespace
